### ISSUE TITLE
当前版本无法创建用户

### ISSUE THREAD

**Issue by kisChang** [open-falcon/dashboard#123]
点击注册按钮，提示页面未找到，日志信息如下：
```2019-01-14 17:08:51 INFO:10.189.15.230 - - [14/Jan/2019 17:08:51] "GET /auth/login HTTP/1.1" 200 -
2019-01-14 17:09:02 INFO:Starting new HTTP connection (1): 127.0.0.1
2019-01-14 17:09:02 DEBUG:"POST /api/v1/user/create HTTP/1.1" 404 125
2019-01-14 17:09:02 DEBUG:404:<!DOCTYPE html>
<html>
<head>
    <title>页面未找到...</title>
</head>
<body>
页面未找到...
</body>
</html>
```
分支: master，58618c6
能不能创建一个单独的开发分支，保证master分支可用

**Comment by kisChang** [comment]
登录也不能用
```
2019-01-14 17:12:23 INFO:Starting new HTTP connection (1): 127.0.0.1
2019-01-14 17:12:23 DEBUG:"POST /api/v1/user/login HTTP/1.1" 404 125
2019-01-14 17:12:23 INFO:10.189.15.230 - - [14/Jan/2019 17:12:23] "POST /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kischang/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kischang/open-falcon/dashboard/rrd/view/auth/auth.py", line 93, in auth_login
    ret["msg"] = str(e)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-54: ordinal not in range(128)
```

**Comment by ppboyhai** [comment]
兄弟，这个问题已经修复了么，我down的最新代码也是这个问题
