### ISSUE TITLE
运行时出现错误， '_compile_builder' it contains a nested function with free variables？

### ISSUE THREAD

**Issue by songcap** [open-falcon/dashboard#139]
CentOS 7.5
错误内容如下：试了很多机子都不行
Traceback (most recent call last):
  File "wsgi.py", line 28, in <module>
    from rrd import app
  File "/home/songhan/dashboard/dashboard/rrd/__init__.py", line 19, in <module>
    from flask import Flask, request
  File "/home/songhan/dashboard/dashboard/env/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/songhan/dashboard/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/home/songhan/dashboard/dashboard/env/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables

这个该如何解决，试了两天没找到解决方法

**Comment by kentwanwan** [comment]
我也是，这个到底是什么问题啊？费劲死了。对flask真的不了解。

**Comment by canghai908** [comment]
升级
```
Werkzeug==0.15.4
```
