### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by xwisen** [open-falcon/dashboard#32]
现象描述:
```shell
#访问前端界面dashboard、screen之外的面板报错如下:
暂时无法访问,请联系管理员.

error: 'NoneType' object has no attribute 'cursor'

traceback日志如下:
Traceback (most recent call last):
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/work/open-falcon/dashboard/rrd/view/portal/home.py", line 19, in home_get
    vs, total = HostGroup.query(page, limit, query, me)
  File "/home/work/open-falcon/dashboard/rrd/model/portal/host_group.py", line 47, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='grp_name')
  File "/home/work/open-falcon/dashboard/rrd/model/portal/bean.py", line 90, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/home/work/open-falcon/dashboard/rrd/model/portal/bean.py", line 86, in select
    return cls._db.query_all(sql, params)
  File "/home/work/open-falcon/dashboard/rrd/store.py", line 95, in query_all
    cursor = self.execute(*a, **kw)
  File "/home/work/open-falcon/dashboard/rrd/store.py", line 58, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

#dashboard 后台报错如下:
mysql config is :{'DB_PASS': '123456', 'DB_NAME': 'falcon_portal', 'DB_USER': 'root', 'DB_HOST': '127.0.0.1', 'DB_PORT': '3306'}
2017-05-04 07:50:18 CRITICAL:connect db: an integer is required
mysql config is :{'DB_PASS': '123456', 'DB_NAME': 'falcon_portal', 'DB_USER': 'root', 'DB_HOST': '127.0.0.1', 'DB_PORT': '3306'}
2017-05-04 07:50:18 CRITICAL:connect db: an integer is required
```

问题原因:
```python
def connect_db(cfg):
    try:
        print("mysql config is :{}".format(cfg))
        conn = MySQLdb.connect(
            host=cfg['DB_HOST'],
            port=int(cfg['DB_PORT']),   //端口号转换为整型就没这问题
            user=cfg['DB_USER'],
            passwd=cfg['DB_PASS'],
            db=cfg['DB_NAME'],
            use_unicode=True,
            charset="utf8")
        return conn
    except Exception, e:
        logging.getLogger().critical('connect db: %s' % e)
        return None
```
* mysql 为docker hub 镜像`mysql:5.7`

**Comment by xwisen** [comment]
自己的锅，配置文件里面写错了！
