### ISSUE TITLE
模板添加策略获取metric列表500

### ISSUE THREAD

**Issue by refinedKing** [open-falcon/dashboard#39]
master 克隆时间:   5月10号

配置:  
dashboard:
API_ADDR = os.environ.get("API_ADDR","http://10.27.10.164:7103/api/v1")

api cfg.json
    "metric_list_file": "/data/apidata/metric",
    "web_port": ":7103",

环境: 
Flask (0.10.1)
gunicorn (18.0)
itsdangerous (0.24)
Jinja2 (2.7.2)
MarkupSafe (1.0)
MySQL-python (1.2.5)
pip (1.4.1)
python-dateutil (2.2)
python-ldap (2.4.38)
requests (2.3.0)
setuptools (0.9.8)
six (1.10.0)
Werkzeug (0.9.4)
wsgiref (0.1.2)

2017-05-12 13:23:58 INFO:10.27.10.164 - - [12/May/2017 13:23:58] "GET /api/metric/query?query=in&limit=10&_=1494556741582 HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/data/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/data/dashboard/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 824, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/data/dashboard/env/lib/python2.7/site-packages/werkzeug/test.py", line 854, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'list' object is not callable

**Comment by laiwei** [comment]
我这里没有问题，检查下api组件关于  "metric_list_file": "/data/apidata/metric" 这块的配置吧

**Comment by refinedKing** [comment]
请问来总,  "metric_list_file": "/data/apidata/metric"    这里metric数据的来源是?  transfer 还是 ?  看了源代码没看出所以然

**Comment by season89** [comment]
这里的metric_list_file中的采集项是默认采集项，仅仅作为文档说明提供了一个查看默认采集了那些数据项项的接口。
api数据来源是transfer
@refinedKing 我理解是这样的，实际情况需要lai总@laiwei看下

**Comment by laiwei** [comment]
@season89 你说的是对的，这个文件是agent采集的标准metric列表，是手工维护的

**Comment by refinedKing** [comment]
@laiwei   原来是手工维护的, 感谢lai总解答
@season89  谢谢

**Comment by toffstechzhang** [comment]
为什么手工维护？怎样维护？
