### ISSUE TITLE
创建策略检索metric报错

### ISSUE THREAD

**Issue by haormj** [open-falcon/dashboard#85]
使用docker运行dashboard
下面是详细日志
```log
2018-01-09 07:39:35 ERROR:400:{"error":"open ./api/data/metric: no such file or directory"}

2018-01-09 07:39:35 INFO:10.44.74.218 - - [09/Jan/2018 07:39:35] "GET /api/metric/query?query=value&limit=10&_=1515482390237 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 824, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/werkzeug/test.py", line 854, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'list' object is not callable
  ```

**Comment by a180285** [comment]
Why just closed? could help share what happened for this issue?
